### ISSUE TITLE
Fail when a package is a non-dev dependency and is only referenced by its scripts

### ISSUE THREAD

**Issue by dustyholmes-wf** [Workiva/dependency_validator#106]
When a package isn't imported, dependency_validator will print the following message if it has bin scripts.

```The following packages contain executables, they are assumed to be used:```

However, a dependency that isn't referenced in lib should always be a dev_dependency. As a result, I propose that if a package is listed under `dependencies` and is unused, but has scripts, then dependency_validator should fail and suggest moving the package into `dev_dependencies`

**Comment by matthewnitschke-wk** [comment]
This has been resolved in the v4 release #111
