### ISSUE TITLE
Is it possible to get JSON output ?

### ISSUE THREAD

**Issue by prasunsultania** [Workiva/dependency_validator#109]
Is it possible to get output as JSON ?

**Comment by matthewnitschke-wk** [comment]
Not currently possible given the current command line arguments / functionality

How are you wanting to use this data? and what are you expecting the output to be?

**Comment by prasunsultania** [comment]
@matthewnitschke-wk 

I have written a tool to validate the PR before merging it so, that any missing/extra dependencies are addressed. 

Below, screenshot will give an idea of what I have been trying to do

![2024-04-25_12-11-05](https://github.com/Workiva/dependency_validator/assets/6882589/4791bba1-5f68-4c5d-88b4-a5a925758f66)

**Comment by matthewnitschke-wk** [comment]
Interesting! Could you just use the stdout from running the `dart run dependency_validator` command? 

Looks like you're just looking for a high level summary of what dependencies might be invalid, which the default stdout already provides

**Comment by prasunsultania** [comment]
@matthewnitschke-wk I can parse the stdout, is the format going to be consistent in future updates ?

**Comment by matthewnitschke-wk** [comment]
No, I don't think so

In your [above example](https://github.com/Workiva/dependency_validator/issues/109#issuecomment-2076483737) it appears as though you are just piping the output of `npx depcheck` to the comments on a jira issue. I didn't realize that you're also trying to parse the data within the result as well

If you could give an example of what data you're trying to parse from the results, that would help us understand how best to format the json output

**Comment by matthewnitschke-wk** [comment]
Closing this due to lack of more information, feel free to re-open if you still desire this functionality
