### ISSUE TITLE
FlutterSDK unavailable

### ISSUE THREAD

**Issue by MikeMannox** [Workiva/dependency_validator#55]
I found this dependency on https://pub.dev/packages/dependency_validator

It says it is Flutter compatible (the dark blue box with Flutter in white)

I added:
```yaml
dev_dependencies:
  dependency_validator: ^1.4.2
```
to the `pubspec.yaml` of Flutter project.

I opened Terminal and CD to the project.
I then enter:
```cli
$ pub run dependency_validator
The Flutter SDK is not available. // <- output
```
On the off chance I though I would try:
```cli
flutter pub run dependency_validator
Failed to precompile build_runner:graph_inspector:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.2.1/lib/src/resolver.dart:263:31: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
  var sdk = FolderBasedDartSdk(resourceProvider, dartSdkFolder, true) // <- output, but this carries on for a while
```

Thanks!

**Comment by evanweible-wf** [comment]
Hello @MikeMannox! I'm able to install and run this tool via `flutter pub run dependency_validator` in a flutter project without any errors on flutter version `1.12.13+hotfix.5 • channel stable`.

The precompilation error you are seeing is from some code in the `build_resolvers` package. Could you try upgrading your `build_resolvers` dependency to see if that helps? If it doesn't, I'd recommend opening an issue over at https://github.com/dart-lang/build/issues

**Comment by MikeMannox** [comment]
It seems you're right, I tried this on another project and it is working as expected.
Thank you, I'll close this.
