### ISSUE TITLE
Analyze analysis_options.yaml as dependency

### ISSUE THREAD

**Issue by fzyzcjy** [Workiva/dependency_validator#88]
For example, its content:

```
include: package:mypackage/my_analysis_options.yaml
```

Then `mypackage` is used indeed.

**Comment by evanweible-wf** [comment]
Hmm, this should already be supported and working:
- https://github.com/Workiva/dependency_validator/blob/master/lib/src/dependency_validator.dart#L71-L72
- https://github.com/Workiva/dependency_validator/blob/master/lib/src/utils.dart#L34-L47
- https://github.com/Workiva/dependency_validator/blob/master/test/executable_test.dart#L478-L520

Do you have a package where this isn't working as expected?

**Comment by fzyzcjy** [comment]
Yes I see it working later. Thanks!
