### ISSUE TITLE
Not properly ignoring "missing packages"

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dependency_validator#9]
From @michaelcarter-wf:

> [1:11 PM] Michael Carter: I can't seem to get dependency_audit to ignore some packages:
>
> ```bash
> $ pub run dependency_validator --ignore coverage,dart_style,dartdoc,over_react_format,semver_audit,designated_driver
>    Validating dependencies for workflow_client
>    These packages are used outside lib/ but are not dev_dependencies:
>      * designated_driver
>      * shelf
>      * shelf_proxy
>      * w_router
>      * w_webdriver_utils
> ```

Note that `designated_driver` is supposed to be ignored but still shows up in the warnings.

**Comment by ugolova** [comment]
Hi! This bug can be closed after this merge: https://github.com/Workiva/dependency_validator/pull/10

Also, please update pub package https://pub.dartlang.org/packages/dependency_validator so we can use fixed version

**Comment by evanweible-wf** [comment]
Fixed in #10 and #12. Thanks again @ugolova! Version 1.0.1 is available now on pub.
