### ISSUE TITLE
Old readme instructions

### ISSUE THREAD

**Issue by guyluz11** [Workiva/dependency_validator#99]
Readme stats to use the command 
`pub run dependency_validator` but it didn't work for me

https://github.com/Workiva/dependency_validator#usage

Found that 
`dart run dependency_validator`
is working

**Comment by Subrataporwal** [comment]
+1

**Comment by matthewnitschke-wk** [comment]
This was addressed in the v4 release: https://github.com/Workiva/dependency_validator/pull/111/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
